Repository parteek10/450DSA, pull requests merged in 2021-10, with the labels that each got.

#6 Max profit at most k transactions
  Dynamic Programming/stockSellKTimes.cpp
Labels: hacktober-accepted

#2 Create kadaneAlgo.cpp
  Array/kadaneAlgo.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#9 Create numericKeypad.cpp
  Dynamic Programming/numericKeypad.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#8 2 CSES DP Solutions added
  cses/Dynamic Programming/dp_edit_distance.cpp
  cses/Dynamic Programming/dp_money_sum.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#7 add diameter of binary tree solution
  Array/kadaneAlgo.cpp
  Binary Tree/180_DiameterOfBinaryTree.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#12 Create NegativetoOneSide.cpp
  Array/NegativetoOneSide.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#10 Create insert_at_given_index_array.cpp
  Array/insert_at_given_index_array.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#11 Create duplicateinArray.cpp
  Array/duplicateinArray.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#13 Create KnapSackProblem.cpp
  Dynamic Programming/KnapSackProblem.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#15 Matrix Chain Multiplication DP problem
  Dynamic Programming/MatrixChainMultiplication.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#14 Edit Distance Standard DP Problem
  Dynamic Programming/EditDistance.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#16 Create Longest Increasing subsequence
  Dynamic Programming/Longest Increasing subsequence
Labels: hacktoberfest-accepted

#21 Create MajorityElementArray.cpp
  Array/MajorityElementArray.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#20 Create BubbleSortOptimized.cpp
  Array/BubbleSortOptimized.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#19 Create SelectionSort.cpp
  Array/SelectionSort.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#18 Maximize cut segment DP
  Dynamic Programming/MaximixeCutSegment.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#17 Create Longest palindromic substring
  Dynamic Programming/Longest palindromic substring
Labels: hacktober-accepted, hacktoberfest-accepted

#29 Top View of Binary Tree
  Binary Tree/top_view_binary_tree.cpp
Labels: hacktoberfest-accepted

#23 right_view_binary_tree solution
  Binary Tree/right_view_binary_tree.cpp
Labels: hacktoberfest-accepted

#30 Kth Ancestor of Binary Tree (using Binary Lifting)
  Binary Tree/kth_ancestor_binary_tree.cpp
Labels: hacktoberfest-accepted

#31 BST isDeadEnd added
  BST/isDeadEnd.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#22 added preorder traversal of Binary tree
  Binary Tree/preorder.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#34 Create ConsecutiveSubsequence.cpp
  Array/ConsecutiveSubsequence.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#33 DP Catalan Numbers
  Dynamic Programming/catalanNumbers.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#32 Added the solution to Stacks #6 problem
  Stacks & Queues/6.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#28 Create MenuDrivenArray.cpp
  Array/MenuDrivenArray.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#27 Create HourGlassArray.cpp
  HourGlassArray.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#26 Create TimeConversion.cpp
  Array/TimeConversion.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#40 binomialCoefficient Dp
  Dynamic Programming/FriendsPairingProblem DP
  Dynamic Programming/binomialCoefficient.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#41 Create Gold Mine DP
  Array/TrappingRainWater.cpp
  Dynamic Programming/Gold Mine DP
Labels: hacktober-accepted, hacktoberfest-accepted

#43 Least Common Ancestor of Binary Tree problem added
  Binary Tree/LCAOfBinaryTree
Labels: hacktober-accepted, hacktoberfest-accepted

#44 BinaryToSumTree
  Binary Tree/BinaryToSumTree.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#35 Create reverseString.cpp
  Array/reverseString.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#46 BinaryToDoublyLinkedList program
  Binary Tree/BinaryToDoublyLinkedList
Labels: hacktober-accepted, hacktoberfest-accepted

#47 Create ZigZagTreeTraversal.cpp
  Binary Tree/ZigZagTreeTraversal.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#51 ReverseLevelOrderTraversal of binary Tree
  Binary Tree/ReverseLevelOrderTraversal.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#52 FactorailofLargerNumber
  Array/FactorailofLargerNumber.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#56 Some of the Binary Tree solution added
  Trees/MaxSuminBinarytreenoAdjacent.cpp
  Trees/MinimumnoofSwapstoBST.cpp
Labels: hacktoberfest-accepted

#57 Longest Consecutive Subsequence
  Array/LongestConsecutiveSubsequence.cpp
Labels: hacktoberfest-accepted

#55 count set bits in a number
  bit_manipuation/count_set_bits_in_number.cpp
  bit_manipulation/bit_to_flipped_to_convert_a_to_b.cpp
Labels: hacktoberfest-accepted

#54 Create SortStackUsingReccursion.cpp
  Stacks & Queues/EvaluatePostfixExpression.cpp
  Stacks & Queues/SortStackUsingReccursion.cpp
Labels: hacktoberfest-accepted

#62 Create MirrorOfTree.cpp
  Binary Tree/MirrorOfTree.cpp
  Matrix/SpiralTraversalOfMatrix.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#61 Created Greedy folder and added 2 files
  Greedy/1.cpp
  Greedy/4.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#60 Create FindtheDuplicateNumber.cpp
  Array/CountPairsWithGivenSum.cpp
  Array/FindtheDuplicateNumber.cpp
  SmallestSubarrayWithSumGreater.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#59 Tree and Linked list solutions of 450DSA sheet
  Linked List/Merge two sorted linked lists.cpp
  Linked List/Reverse a Linked List in group of Given Size.cpp
  Trees/Bottom view of a tree.cpp
  Trees/Top view of a tree.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#45 Knapsack Problem
  cses/Dynamic Programming/knapsack 0-1 dp.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#36 Added the Solution To Check whether a String is Palindrome or not, Find the triplet that sum to a given value, Find median in a row wise sorted matrix
  Array/27.cpp
  Matrix/2.cpp
  String/1.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#63 Create SubsequenceProductLessThanK.cpp
  Dynamic Programming/SubsequenceProductLessThanK.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#69 coinChange and minimumJumps
  Array/minimumJumps.cpp
  Dynamic Programming/coinChange.cpp
Labels: hacktoberfest-accepted

#68 Create 18_CommonElements.cpp
  Array/18_CommonElements.cpp
Labels: hacktoberfest-accepted

#67 Added Subset sum problem code
  Dynamic Programming/7_subsetSumProblem.cpp
Labels: hacktoberfest-accepted

#65 Reverse the array
  Array/0_Find the "Kth" max and min element of an array.cpp
  Array/0_Find the maximum and minimum element in an array.cpp
  Array/Reverse the array 3
Labels: hacktoberfest-accepted

#70 Create 9_celebrityProblem.cpp
  Stacks & Queues/9_celebrityProblem.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#71 Balanced_Paranthesis.cpp
  Stacks & Queues/5_Balanced_Paranthesis.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#73 Create 17_SumPairs.cpp
  Array/17_SumPairs.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#72 Create LongestRepeatingSubsequence.cpp
  String/LongestRepeatingSubsequence.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#74 3_Permutation_Coefficient.cpp
  Dynamic Programming/3_Permutation_Coefficient.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#78 Added miscellaneous files
  Binary Tree/0_LevelOrderTraversal.cpp
  Binary Tree/2_HeightOfBT.cpp
  Greedy/1_JobSchedulingProblem.cpp
  Greedy/4_FractionalKnapsack.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#79 matrix-Q.9 Added
  Matrix/9_commonElementsInAllRowsOfMatrix.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#77 equal subset sum dp problem added
  Array/sortArrayByparityII.cpp
  Binary Tree/preorder.cpp
  Dynamic Programming/equalSubsetSum.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#76 Create BinaryTreeToBST.cpp
  BST/BinaryTreeToBST.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#75 Maximum and minimum element in array
  Array/1_max and min element(divide-conquer).cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#81 Create LCA of a given node
  BST/LCA of a given node
Labels: hacktoberfest-accepted

#80 Create Kth smallest element in a BST
  BST/Kth smallest element in a BST
Labels: hacktoberfest-accepted

#82 Added algorithm resource readme
  Algorithms-helpbook.md
Labels: hacktoberfest-accepted

#83 Added counting sort pseudo code as requested
  Algorithms-helpbook.md
  README.md
Labels: hacktoberfest-accepted

#84 Rename files as per #66 issue
  bit_manipulation/0_countSetBits.cpp
  bit_manipulation/2_bitFlippedConvertAtoB.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#88 added => heap => heapsort
  heap/ques_01_heapsort.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#87 added => search and sort => find majority element
  search_and_sort/ques_07.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#85 added => Greedy => activity_selection.cpp
  Greedy/Activity_selection.cpp
  search_and_sort/q0_first_and_last_pos.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#86 15_count_inversion.cpp
  Array/15_count_inversion.cpp
  Dynamic Programming/permutation_coefficient.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#95 Dijkstras_algo.cpp
  Graph/Dijkstras_algo.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#94 Array solution
  Array/40-Median-Of-2-sorted-arrays-of-Equal-Size.cpp
  Array/41-Median-of-2-sorted-arrays-of-diiferent-sizes.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#93 Create Check-if-a-Given-String-is-Palindrome.cpp
  String/Check-if-a-Given-String-is-Palindrome.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#92 Create 11_combinationsum.cpp
  Backtracking/11_combinationsum.cpp
  Backtracking/13_Printallpermutationsofastring.cpp
  search_and_sort/21_findpivotofelementinsortedarray.cpp
  search_and_sort/2_searchinarotatedsortedarray.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#91 Add linked list qus
  Linked List/0_Write_a_Program_to_reverse_the_Linked_List_Both_Iterative_and_recursive.cpp
  Linked List/10_Intersection_of_two_Sorted_Linked_List.cpp
  Linked List/11_Intersection_Point_of_two_Linked_Lists.cpp
  Linked List/3_Write_a_program_to_Delete_loop_in_a_linked_list.cpp
  Linked List/4_Find_the_starting_point_of_the_loop.cpp
  Linked List/5_Remove_Duplicates_in_a_sorted_Linked_List.cpp
  Linked List/7_Write_a_Program_to_Move_the_last_element_to_Front_in_a_Linked_List.cpp
  Linked List/8_Add-1-to_a_number_represented_as_a_Linked_List.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#90 Create 0_ReverseTheString.cpp
  String/0_ReverseTheString.cpp
  search_and_sort/1_FixedPointInGivenArray.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#24 Create quickSort.cpp
  Array/quickSort.cpp
Labels: hacktoberfest-accepted

#99 Kruskals_algo.cpp
  Graph/Kruskals_algo.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#98 LeetCode Leaf Similar Tree Problem added
  Binary Tree/LeafSimilarTrees.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#97 Create 3_SquareRootOfAnInteger.cpp
  search_and_sort/3_SquareRootOfAnInteger.cpp
Labels: hacktober-accepted, hacktoberfest-accepted

#96 Greedy solutions
  Greedy/240-Huffman-Coding.cpp
  Greedy/251-Find-Max-Meetings-in-one-room.cpp
Labels: hacktober-accepted, hacktoberfest-accepted
